In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/volodymyrgavrysh/bank-marketing-campaigns-dataset/bank-additional-full.csv

# Ordinal Features Encoding

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("volodymyrgavrysh/bank-marketing-campaigns-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/volodymyrgavrysh/bank-marketing-campaigns-dataset

In [3]:
import pandas as pd
df = pd.read_csv("/kaggle/input/datasets/volodymyrgavrysh/bank-marketing-campaigns-dataset/bank-additional-full.csv", sep=';')

# Ordinal Encoding
**Used to label ordinal input data**

In [4]:
df.sample(5)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
3361,44,blue-collar,married,basic.4y,no,no,yes,telephone,may,thu,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,no
39944,36,admin.,married,university.degree,no,yes,yes,cellular,jun,fri,...,1,4,4,success,-1.7,94.055,-39.8,0.748,4991.6,no
2145,53,retired,divorced,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5346,49,technician,married,unknown,no,yes,no,telephone,may,fri,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
30573,22,student,single,high.school,no,yes,yes,cellular,may,mon,...,3,999,0,nonexistent,-1.8,92.893,-46.2,1.354,5099.1,yes

In [5]:
df["education"].unique()

array(['basic.4y', 'high.school', 'basic.6y', 'basic.9y',
       'professional.course', 'unknown', 'university.degree',
       'illiterate'], dtype=object)

In [6]:
df = df[["education","housing"]]
df

                 education housing
0                 basic.4y      no
1              high.school      no
2              high.school     yes
3                 basic.6y      no
4              high.school      no
...                    ...     ...
41183  professional.course     yes
41184  professional.course      no
41185    university.degree     yes
41186  professional.course      no
41187  professional.course     yes

[41188 rows x 2 columns]

In [7]:
df["housing"].unique()

array(['no', 'yes', 'unknown'], dtype=object)

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
import numpy as np
#array = np.array()
oe = OrdinalEncoder(categories=[["unknown","illiterate","basic.4y","basic.6y","basic.9y",'high.school','professional.course','university.degree'],['no', 'yes', 'unknown']] )
oe

OrdinalEncoder(categories=[['unknown', 'illiterate', 'basic.4y', 'basic.6y',
                            'basic.9y', 'high.school', 'professional.course',
                            'university.degree'],
                           ['no', 'yes', 'unknown']])

In [10]:
import numpy as np
arr_df=np.array(df)
oe.fit( arr_df)

OrdinalEncoder(categories=[['unknown', 'illiterate', 'basic.4y', 'basic.6y',
                            'basic.9y', 'high.school', 'professional.course',
                            'university.degree'],
                           ['no', 'yes', 'unknown']])

In [11]:
transformed_df=oe.transform(arr_df)
transformed_df

array([[2., 0.],
       [5., 0.],
       [5., 1.],
       ...,
       [7., 1.],
       [6., 0.],
       [6., 1.]], shape=(41188, 2))

In [12]:
import pandas as pd
dff=pd.DataFrame(transformed_df, columns=["education","housing"])
dff
#df

       education  housing
0            2.0      0.0
1            5.0      0.0
2            5.0      1.0
3            3.0      0.0
4            5.0      0.0
...          ...      ...
41183        6.0      1.0
41184        6.0      0.0
41185        7.0      1.0
41186        6.0      0.0
41187        6.0      1.0

[41188 rows x 2 columns]

# Label Encoding
**Used for encoding ordinal labels (output)**

In [13]:
df = pd.read_csv("/kaggle/input/datasets/volodymyrgavrysh/bank-marketing-campaigns-dataset/bank-additional-full.csv", sep=';')

In [14]:
df.sample(3)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
38690,26,admin.,single,high.school,no,unknown,unknown,cellular,nov,mon,...,1,999,0,nonexistent,-3.4,92.649,-30.1,0.715,5017.5,yes
1249,43,blue-collar,married,basic.4y,unknown,yes,no,telephone,may,thu,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
30793,44,admin.,married,university.degree,no,yes,no,cellular,may,tue,...,1,999,0,nonexistent,-1.8,92.893,-46.2,1.344,5099.1,no

In [15]:
df =df["y"]
df

0         no
1         no
2         no
3         no
4         no
        ...
41183    yes
41184     no
41185     no
41186    yes
41187     no
Name: y, Length: 41188, dtype: object

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le= LabelEncoder()

In [18]:
le.fit(df)

LabelEncoder()

In [19]:
encoded_df= le.transform(df)

In [20]:
encoded_df

array([0, 0, 0, ..., 0, 1, 0], shape=(41188,))

In [21]:
le.classes_

array(['no', 'yes'], dtype=object)

# Nominal Data Encoding
**One hot encoding is used for nominal data encoding**

In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("/kaggle/input/datasets/volodymyrgavrysh/bank-marketing-campaigns-dataset/bank-additional-full.csv", sep=';')

In [24]:
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [25]:
#nominal encoding with pandas

df_ohe=pd.get_dummies(df, columns= ['contact','marital'])

In [26]:
df_ohe.sample(5)

,age,job,education,default,housing,loan,month,day_of_week,duration,campaign,...,cons.conf.idx,euribor3m,nr.employed,y,contact_cellular,contact_telephone,marital_divorced,marital_married,marital_single,marital_unknown
24355,38,blue-collar,basic.4y,no,no,no,nov,mon,112,1,...,-42.0,4.191,5195.8,no,True,False,False,True,False,False
97,53,admin.,university.degree,unknown,no,no,may,mon,287,1,...,-36.4,4.857,5191.0,no,False,True,True,False,False,False
34496,36,management,university.degree,no,yes,no,may,thu,128,1,...,-46.2,1.266,5099.1,no,True,False,False,True,False,False
34430,31,entrepreneur,university.degree,no,yes,no,may,thu,633,1,...,-46.2,1.266,5099.1,yes,True,False,False,False,True,False
14218,35,blue-collar,high.school,no,yes,no,jul,mon,105,3,...,-42.7,4.962,5228.1,no,True,False,False,True,False,False

In [27]:
#k-1 one hot encoding (remove collinearity ie dropping one columns)
df_ohe_k_1 = pd.get_dummies(df, columns=['marital', 'contact'], drop_first=True)

In [28]:
df_ohe_k_1.sample(5)

,age,job,education,default,housing,loan,month,day_of_week,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,marital_married,marital_single,marital_unknown,contact_telephone
40127,35,technician,professional.course,no,yes,no,jul,tue,360,1,...,-1.7,94.215,-40.3,0.835,4991.6,yes,False,True,False,False
21396,58,unknown,basic.4y,no,yes,no,aug,tue,645,10,...,1.4,93.444,-36.1,4.963,5228.1,yes,True,False,False,False
8381,36,admin.,professional.course,no,yes,no,jun,tue,129,1,...,1.4,94.465,-41.8,4.864,5228.1,no,True,False,False,True
3458,60,entrepreneur,basic.4y,no,unknown,unknown,may,thu,101,3,...,1.1,93.994,-36.4,4.860,5191.0,no,True,False,False,True
8654,37,unemployed,professional.course,unknown,no,no,jun,wed,42,16,...,1.4,94.465,-41.8,4.864,5228.1,no,True,False,False,True

# One Hot Encoding With SciKit Learn

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
ohe= OneHotEncoder(drop='first')

In [31]:
ohe.fit(df[["contact","marital"]])

OneHotEncoder(drop='first')

In [32]:
encoded_df = ohe.transform(df[['contact','marital']])

In [33]:
 encoded_df = encoded_df.toarray()
 encoded_df

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.]], shape=(41188, 4))

In [34]:
df = df['age']

In [35]:
#now i want to concatenat / horizantally stack the encoded array with the df

In [36]:
df_arr = df.values
df_arr=df_arr.reshape(-1,1) # a 2D array with one element in each 1D array. making it 2D was essential for horizontal stack with a 2D array.
df_arr

array([[56],
       [57],
       [37],
       ...,
       [56],
       [44],
       [74]], shape=(41188, 1))

In [37]:
import numpy as np
encoded_df_final = np.hstack((encoded_df,df_arr))

In [38]:
encoded_df_final

array([[ 1.,  1.,  0.,  0., 56.],
       [ 1.,  1.,  0.,  0., 57.],
       [ 1.,  1.,  0.,  0., 37.],
       ...,
       [ 0.,  1.,  0.,  0., 56.],
       [ 0.,  1.,  0.,  0., 44.],
       [ 0.,  1.,  0.,  0., 74.]], shape=(41188, 5))

In [39]:
df = pd.read_csv("/kaggle/input/datasets/volodymyrgavrysh/bank-marketing-campaigns-dataset/bank-additional-full.csv", sep=';')

In [40]:
counts=df["month"].value_counts()
counts

month
may    13769
jul     7174
aug     6178
jun     5318
nov     4101
apr     2632
oct      718
sep      570
mar      546
dec      182
Name: count, dtype: int64

In [41]:
#i want months with less than 1000 existences ie value counts, i want gather all of them in a new column named "uncommon"

In [42]:
threshold = 1000
uncommon_months=counts [ counts<threshold].index
uncommon_months

Index(['oct', 'sep', 'mar', 'dec'], dtype='object', name='month')

In [43]:
pd.get_dummies(df['month'].replace(uncommon_months, "uncommon"), drop_first= True)

         aug    jul    jun    may    nov  uncommon
0      False  False  False   True  False     False
1      False  False  False   True  False     False
2      False  False  False   True  False     False
3      False  False  False   True  False     False
4      False  False  False   True  False     False
...      ...    ...    ...    ...    ...       ...
41183  False  False  False  False   True     False
41184  False  False  False  False   True     False
41185  False  False  False  False   True     False
41186  False  False  False  False   True     False
41187  False  False  False  False   True     False

[41188 rows x 6 columns]