<a href="https://www.kaggle.com/code/mumerfarooqbajwa/cleaning-messy-clinic-appointments-dataset?scriptVersionId=338085141" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/nudratabbas/messy-clinic-appointments-dataset/messy_clinic_appointments.csv

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nudratabbas/messy-clinic-appointments-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/nudratabbas/messy-clinic-appointments-dataset

In [3]:
import pandas as pd
import numpy as np

from sklearn import set_config
set_config(transform_output='pandas')

In [4]:
df = pd.read_csv("/kaggle/input/datasets/nudratabbas/messy-clinic-appointments-dataset/messy_clinic_appointments.csv")
df.sample(10)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
266,1088,Amy King,49,Female,15-Sep-2025,2025/01/30,Peter Wells,General,£241.48,Y
990,1052,Nicholas Mcdaniel,48,F,"August 09, 25",2025/04/26,Daniel Smith,Orthopedics,€79.73,0
55,1068,Vanessa Jones,63,F,2025/11/09,10-Sep-2025,Courtney Knight,Orthopedics,$169.25,Yes
394,1005,Mr. Phillip Baxter,80,M,07/24/2025,01/16/2025,Tricia Hunt,General,$320.72,N
257,1056,Joshua Sanford,57,female,2025/06/20,13-Feb-2025,Tara Montoya,Neurology,$186.61,1
245,1060,Haley Taylor,51,female,2025/07/06,04/18/2025,Christopher Wolfe,General,Rs433.55,Y
584,1069,Jacqueline Peters,40,0,2025/12/09,11-Oct-2025,Adam Jensen,General,€266.74,Yes
934,1091,Scott Walker,62,Male,03/22/2026,2025/11/28,Brianna Hernandez,Neurology,$433.63,Y
401,1074,Michelle Edwards,30,female,03-Dec-2025,07/27/2025,Charles Harvey,Orthopedics,£242.2,Yes
757,1018,Joel Marshall,55,1,12/23/2025,23-Feb-2025,Victoria Garcia,Neurology,€306.8,0

# **Preprocessing/Cleaning of Messy Data**

In [5]:
df['gender'].unique()

array(['female', 'F', 'M', nan, '1', 'Female', 'male', 'Male', '0'],
      dtype=object)

In [6]:
df['gender'].str.lower()

0      female
1           f
2           m
3           f
4         NaN
        ...
995    female
996         f
997         1
998         f
999      male
Name: gender, Length: 1000, dtype: object

In [7]:
df['gender']= np.where(
    (df['gender'].str.lower() == 'female' ) | (df['gender']=='F') |(df['gender']=='0') ,
    'F',
    np.where(
        (df['gender'].str.lower() == 'male') | (df['gender']=='M') |(df['gender']=='1') ,
            'M',
        df['gender']
    )
)

In [8]:
df['gender'].unique()

array(['F', 'M', nan], dtype=object)

# Change the 'appointment_date' Column to Same Date Format

In [9]:
df['appointment_date']

0            2026/02/26
1            05/23/2025
2           30-Nov-2025
3            May 18, 25
4            2026/03/07
             ...
995    September 14, 25
996        April 09, 25
997     February 13, 26
998          2025/07/04
999         05-Nov-2025
Name: appointment_date, Length: 1000, dtype: object

In [10]:
df['appointment_date']= pd.to_datetime(df['appointment_date'],format='mixed')

In [11]:
df['appointment_date'].isnull().sum()

np.int64(0)

# Change 'booking_date' Column to Same Format of DateTime

In [12]:
df['booking_date']

0         2024/12/03
1        12-Jun-2024
2      August 05, 24
3         09/09/2024
4         08/17/2024
           ...
995       2024/07/15
996      June 20, 24
997       2024/06/13
998       2024/04/15
999       2024/07/22
Name: booking_date, Length: 1000, dtype: object

In [13]:
df['booking_date'] = pd.to_datetime(df['booking_date'], format='mixed'	)

In [14]:
df['booking_date']

0     2024-12-03
1     2024-06-12
2     2024-08-05
3     2024-09-09
4     2024-08-17
         ...
995   2024-07-15
996   2024-06-20
997   2024-06-13
998   2024-04-15
999   2024-07-22
Name: booking_date, Length: 1000, dtype: datetime64[ns]

In [15]:
df['booking_date'].isnull().sum()

np.int64(0)

# Splitting 'billing_amount' Column to Get billing_amount in Same Currency

In [16]:
df['billing_amount'].unique()

array(['£425.8', '€344.26', '€203.34', 'Rs85.76', '$84.44', nan, '€99.0',
       'Rs374.63', '$452.37', '€494.97', '£91.91', '$82.88', 'Rs277.14',
       '€411.01', '£67.51', '€163.99', '£252.38', '$153.07', 'Rs329.3',
       '€135.45', 'Rs72.73', 'Rs258.64', '$203.61', 'Rs236.22',
       'Rs292.23', '$51.72', '£218.84', 'Rs160.38', 'Rs342.38',
       'Rs208.91', 'Rs426.86', '£215.31', '£413.53', '£396.22', '$340.25',
       '$481.44', '$442.77', 'Rs175.63', '€320.66', '$268.14', '€499.75',
       'Rs452.11', 'Rs479.77', '£213.35', 'Rs120.34', 'Rs135.43',
       '€214.44', 'Rs376.08', '€343.51', 'Rs185.66', '€200.01', '$367.06',
       'Rs393.4', '£387.4', '$169.25', '$274.81', 'Rs68.81', 'Rs365.13',
       '$466.97', 'Rs484.52', '€114.45', '€195.21', '$149.8', 'Rs270.33',
       '$186.24', 'Rs425.63', '£91.77', '€91.27', '£453.06', '€61.37',
       '$185.52', '£112.48', '$382.34', 'Rs168.18', '$206.53', '$258.21',
       '€253.4', 'Rs83.09', '$80.38', 'Rs260.4', '$294.58', '$247.13',
       '£341.19', 'Rs383.69', '€243.78', 'Rs329.25', '€389.37', '£344.56',
       'Rs289.07', 'Rs193.6', 'Rs259.72', '€235.69', '€428.75', '$142.32',
       '£109.31', '$325.25', '£111.92', '$347.68', '£59.67', 'Rs123.03',
       'Rs420.58', '€351.17', '£125.31', '€253.42', '€359.78', '$277.21',
       '£84.69', '€96.94', 'Rs205.35', 'Rs155.42', '$493.0', '$243.15',
       '€122.6', '£100.34', 'Rs335.07', '£154.29', '$412.07', 'Rs401.33',
       '$486.57', '£482.25', '€255.82', '€258.12', '$162.94', '£153.05',
       '£114.64', '£381.62', '£215.46', '$455.75', '£325.97', '$468.06',
       '£377.14', '$87.2', '$226.97', 'Rs139.81', '$466.08', 'Rs352.03',
       '$461.19', '£252.22', '£206.74', '$130.7', '£106.33', '$122.56',
       '£238.81', 'Rs413.21', '€91.87', '€485.5', '£209.81', '$401.55',
       'Rs283.3', '£146.2', '€211.18', '£476.99', '$248.33', '£192.67',
       '$65.06', '£117.14', 'Rs433.77', '$82.84', 'Rs216.23', '€492.98',
       'Rs280.77', '$99.19', '$225.83', '$458.12', '€244.78', '€330.37',
       '£98.14', '£464.69', '£91.65', 'Rs425.67', '€140.86', '$446.06',
       '£138.59', '£448.6', '€150.94', '€339.19', '€187.28', '€157.66',
       'Rs69.97', '£490.55', '€315.64', '£231.08', '$429.14', 'Rs93.12',
       '£461.81', '€130.72', 'Rs85.63', '€394.9', '£499.67', '€66.64',
       'Rs361.31', '£205.31', 'Rs193.18', '£321.34', '$446.44', '$165.8',
       'Rs493.59', '€489.64', '$96.48', '€422.79', 'Rs330.43', '£440.72',
       '€287.03', '€489.0', '£201.19', '€155.45', '£236.44', '$96.21',
       '€270.47', 'Rs284.29', '€354.36', '£452.69', '£329.83', '€450.86',
       'Rs132.38', '€199.55', '€296.7', '$409.96', '£386.53', 'Rs243.94',
       '$364.83', '$335.95', '€387.58', 'Rs360.39', '£288.24', '€286.43',
       '€476.26', '£480.75', 'Rs277.6', 'Rs301.11', '£304.51', '£266.53',
       'Rs433.55', '£70.47', '$425.91', '€111.71', '£365.37', '€475.27',
       '$108.6', '£455.05', '£264.45', 'Rs132.57', 'Rs359.5', 'Rs464.57',
       '$186.61', '$116.69', '€218.44', '€255.67', '$129.48', 'Rs299.03',
       'Rs459.66', '£403.61', '£241.48', '$417.38', 'Rs390.97', 'Rs100.2',
       '£462.97', '$481.92', '£350.41', 'Rs392.87', '$202.41', '$225.1',
       '€400.01', '$400.52', '£152.7', '€154.68', '$300.71', '£166.59',
       '£357.83', 'Rs458.11', '€85.07', '£209.67', '£239.39', 'Rs398.73',
       '€325.86', '$451.11', '£416.39', '€303.42', '$124.85', '$370.37',
       'Rs416.85', '£231.18', 'Rs119.4', '$63.38', 'Rs341.27', '$483.19',
       '€371.49', '€406.43', '€334.38', 'Rs125.6', '£377.85', '£450.24',
       '€382.81', '$424.21', '€258.38', 'Rs366.15', 'Rs466.92', '£114.67',
       'Rs71.67', 'Rs264.27', 'Rs92.45', 'Rs441.33', 'Rs258.78',
       'Rs156.71', 'Rs110.47', '€361.32', '€405.85', 'Rs496.78',
       '$364.33', 'Rs119.63', '£399.55', 'Rs186.4', 'Rs234.99',
       'Rs316.26', 'Rs129.91', '€468.01', 'Rs459.41', '€370.25',
       'Rs145.83', '$184.28', '£109.61', '$135.41', '£109.02', '$205.16',
       '$296.43', '$233.98', '€474.34', '£317.84', 'Rs435.55', 'Rs88.58',
       '€252.38', '$366.49', 'Rs239.5', 'Rs55.55', '£112.28', 'Rs386.16',
       '€230.73', '€296.85', '£64.79', '€101.1', 'Rs204.86', '$369.12',
       'Rs474.33', '€285.97', '€209.27', 'Rs347.87', '€98.07', 'Rs154.03',
       '£126.87', '£194.82', '€145.75', '€58.55', '$481.22', '€56.37',
       '£456.26', '$157.36', '$69.13', '€56.63', '$432.84', '£208.8',
       '$413.25', '$73.59', 'Rs466.72', '€213.67', '$156.9', '£323.18',
       '$188.72', '£411.32', '€388.8', '$296.8', '€439.46', '$320.72',
       '$262.84', 'Rs274.94', '£182.77', '€312.88', '£163.58', 'Rs135.85',
       '£242.2', '$374.72', '€326.58', '$379.39', 'Rs442.41', '€358.98',
       '£235.74', '$400.6', '€305.19', '£357.15', '$245.21', 'Rs498.26',
       'Rs499.72', '€315.71', '$149.33', '$412.82', '£372.5', '£60.76',
       '€290.52', 'Rs451.66', '£260.91', '$117.12', 'Rs460.11', '€91.94',
       '£347.38', 'Rs288.43', '€222.2', 'Rs180.6', '€485.31', '£255.9',
       '€443.13', 'Rs318.88', '$108.91', '£167.18', '£444.67', '$396.57',
       'Rs185.29', '$215.89', '£438.81', '€231.7', '£173.85', '$285.44',
       'Rs202.92', '€383.47', '£302.66', '£472.57', '€417.21', '$244.68',
       '$70.7', '€386.37', '$387.75', 'Rs176.68', 'Rs491.64', '$325.91',
       '$280.21', 'Rs88.29', '$443.75', '$385.61', 'Rs350.5', '$255.56',
       '£458.83', '€138.29', 'Rs189.02', '€272.47', '€450.37', '$490.67',
       '£99.17', '$105.64', '€437.18', 'Rs77.2', '€118.72', '€155.69',
       '$487.57', 'Rs412.44', '£297.5', '€481.4', '$252.53', '€167.8',
       'Rs347.94', '£305.02', '€83.61', '£360.39', '€402.4', '£234.26',
       'Rs219.5', '€191.19', 'Rs318.15', '$350.0', 'Rs178.28', '$248.31',
       'Rs352.72', '€208.03', '£116.75', '€91.29', '€198.61', '€257.17',
       '$343.79', '$431.21', '£241.91', '€95.25', '£167.07', '€426.64',
       '€106.8', '$478.18', 'Rs435.1', '€403.22', '€390.81', '£310.42',
       '$469.3', '€495.94', '€403.87', 'Rs466.56', '$163.52', 'Rs356.13',
       '$400.62', '$177.93', '£313.04', '£424.5', 'Rs222.37', '€349.49',
       '$482.2', 'Rs92.08', '€439.56', 'Rs473.48', '€151.02', 'Rs79.59',
       '£167.31', 'Rs194.81', '$97.67', '£254.91', '$169.09', 'Rs94.19',
       '£84.87', '$338.43', '$453.66', '£328.88', '£51.93', 'Rs201.8',
       '$129.1', '$153.53', 'Rs222.33', 'Rs403.78', '$343.21', '£67.97',
       'Rs365.21', '£269.53', '$163.58', 'Rs499.36', 'Rs101.37',
       '£442.72', '£224.89', 'Rs163.4', '€202.98', 'Rs257.1', '€466.87',
       '€490.78', 'Rs217.86', '$174.04', '€196.21', 'Rs490.08', '$91.94',
       '€484.82', '$175.26', 'Rs484.93', '$381.93', 'Rs402.6', 'Rs241.81',
       'Rs467.2', '£148.74', '£109.72', '£477.53', '€286.71', '£316.89',
       '€266.74', '£175.09', 'Rs96.2', 'Rs443.12', '$351.94', '$59.55',
       '£339.57', 'Rs344.57', '$197.72', '£202.68', '$95.4', '€245.84',
       '€284.66', 'Rs389.49', '$161.5', '£68.36', '£332.15', '£294.14',
       '€202.54', 'Rs455.57', '£378.58', '£110.44', '£274.12', 'Rs224.83',
       '$194.55', '€207.23', '€464.96', '£316.64', 'Rs139.49', '€447.23',
       '€320.38', '$212.66', 'Rs390.86', '$136.23', 'Rs68.8', '€79.41',
       'Rs224.61', '$190.44', '$316.64', 'Rs308.59', '$414.58', '€338.24',
       '€53.35', '$186.43', 'Rs268.93', '€322.0', '$498.84', 'Rs415.78',
       'Rs274.5', '£368.24', 'Rs353.07', '£358.68', '$427.54', 'Rs433.05',
       '€436.91', '€252.53', '$421.74', '£175.6', 'Rs203.05', '£123.13',
       '$337.15', '€180.76', '$445.97', '£236.58', '$125.33', '€394.58',
       '€96.12', 'Rs305.01', '$169.01', '€304.86', 'Rs426.51', '$215.76',
       '$184.11', 'Rs226.12', 'Rs277.5', 'Rs63.99', 'Rs85.56', '€237.1',
       '€250.69', '$421.57', '€77.79', '€156.32', '$249.74', '$126.56',
       '$143.32', '£353.8', '£174.54', '£217.77', 'Rs277.51', '£259.19',
       'Rs492.92', '€51.38', 'Rs374.03', '£175.33', '£129.25', 'Rs257.41',
       '€337.48', '€310.15', '€63.14', '$265.67', '$382.64', 'Rs125.35',
       '£206.69', '£358.45', '€496.62', 'Rs290.47', '€346.4', '$123.28',
       '$353.09', 'Rs299.12', '€286.79', '€330.76', '€69.76', '$341.11',
       '$147.08', '$462.6', '€357.53', 'Rs353.35', '£174.42', 'Rs449.41',
       '$179.07', 'Rs344.67', '$84.72', '£479.79', '€77.99', 'Rs113.2',
       '£363.04', '$477.72', 'Rs289.74', '$270.15', '£155.98', 'Rs335.27',
       'Rs285.22', 'Rs91.36', 'Rs498.58', '€453.73', '£218.54',
       'Rs312.26', '€159.21', '€484.79', 'Rs475.35', '$156.1', '$246.13',
       'Rs340.54', '$235.81', '£166.21', '€418.29', '£415.35', '$307.29',
       'Rs268.75', '€248.97', '$270.71', '$253.36', '$192.87', 'Rs362.08',
       '£306.62', '$348.18', '£298.42', '$473.2', '$124.09', '€52.32',
       '$151.03', 'Rs417.42', '$112.9', 'Rs126.44', '€185.15', '€258.9',
       '€477.08', '€306.8', 'Rs190.01', 'Rs281.44', 'Rs252.73', '£397.0',
       'Rs392.0', '€156.61', 'Rs81.87', '£438.16', '£447.77', '$139.99',
       '£393.1', '£248.78', '£453.09', '€57.05', '£386.04', '£204.82',
       '€239.93', 'Rs486.07', '€73.35', '£144.78', '€92.16', 'Rs164.9',
       '$74.84', 'Rs230.11', '€304.67', '£275.12', '€177.85', 'Rs410.8',
       '$97.46', 'Rs116.32', '$203.3', '$139.43', '$74.36', '€303.91',
       '$77.48', '€282.36', '£243.46', '€444.38', 'Rs319.04', '£330.71',
       'Rs160.18', '$290.14', '€244.09', '£150.5', '$398.47', '£262.16',
       '$142.33', 'Rs476.81', '€351.04', '£73.97', '$295.71', 'Rs167.5',
       '£321.5', '$168.33', '€411.75', '£462.15', '€124.69', '€129.38',
       '$488.54', '£93.45', '€73.45', '$340.47', '£414.94', '€238.05',
       'Rs63.62', '$101.59', '$498.48', '$305.84', 'Rs160.05', '$406.61',
       '£359.32', '$315.17', '£319.92', '£352.01', '£88.56', '$461.18',
       'Rs206.57', '£107.34', '$385.01', '£490.93', '$168.86', '$463.06',
       '$261.87', 'Rs170.53', '$197.66', '£454.23', '€104.3', '$263.1',
       '£229.44', '£424.53', '$248.84', '$89.38', '€110.8', '$217.51',
       '€427.98', '$298.89', '£182.71', '€350.12', '€158.91', '£457.94',
       '€130.9', '$318.44', 'Rs291.99', '$161.56', '€79.8', 'Rs151.58',
       'Rs338.13', '€441.92', 'Rs114.73', '£405.59', '$368.56',
       'Rs496.31', '€213.17', '€150.15', '€371.69', '$431.45', '£189.17',
       '$281.71', '€309.31', 'Rs57.03', 'Rs219.97', '£186.51', '€77.05',
       '£208.72', '£390.16', '£74.78', '$199.03', '£245.09', '£282.03',
       'Rs411.85', '£144.89', 'Rs198.95', 'Rs246.05', '€164.43',
       'Rs381.59', '€341.42', 'Rs456.12', 'Rs371.84', '€263.23',
       '$427.62', '£100.78', '£308.28', '€471.3', 'Rs437.95', 'Rs461.32',
       '€424.17', '€428.7', '€159.11', '$159.06', 'Rs317.16', '€470.63',
       '$153.44', '€416.08', '€458.79', '$125.8', 'Rs352.94', '€111.4',
       '€161.54', 'Rs479.37', '$306.94', '€194.95', '€91.05', '€290.36',
       '$85.53', '€419.74', '$83.67', 'Rs255.43', '$433.63', 'Rs461.04',
       '£261.01', 'Rs96.19', '£248.76', 'Rs246.63', 'Rs256.59', '$326.84',
       '£476.97', '$136.77', '€466.59', '€342.3', '€444.2', 'Rs421.18',
       '€386.3', 'Rs107.04', '£381.15', '€477.98', '€418.27', '€300.52',
       '£485.93', '£164.2', '$390.1', '£407.7', 'Rs467.55', '€119.41',
       '£441.89', 'Rs184.38', '$269.35', 'Rs363.94', '£323.0', '$163.0',
       'Rs254.14', '$112.79', 'Rs164.15', '€94.37', '$368.53', 'Rs240.37',
       '£238.59', 'Rs279.32', 'Rs114.8', '€96.78', '£384.42', 'Rs187.7',
       '£382.67', '€236.27', '$359.17', 'Rs362.65', '£401.58', '$120.7',
       '£405.15', '$263.3', '£470.08', '€79.73', '£376.76', 'Rs378.92',
       '$370.13', 'Rs377.38', 'Rs200.43', 'Rs244.49', '£154.48',
       '$434.95', '€102.23'], dtype=object)

In [17]:
df[ ((df['billing_amount'].str[0]!='£') &  (df['billing_amount'].str[0] != '€') & (df['billing_amount'].str[0] != '$') & (df['billing_amount'].str[0] != "R"))] 
# only four currencies
# £, €, Rs, $

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
5,1057,Joe Sharp,78,M,2025-09-26,2025-08-31,Kimberly Fields,General,NaN,Yes
33,1041,Nicole Shaw,20,M,2025-05-07,2025-01-19,Mr. Brian Morton,Neurology,NaN,Y
75,1061,Jessica Smith,66,F,2025-08-20,2025-03-08,Crystal Mack,Neurology,NaN,Yes
97,1052,Keith Becker,60,F,2025-11-07,2024-08-28,Kristopher Collier,General,NaN,Y
140,1069,Thomas Landry,60,M,2025-09-03,2025-08-01,Brandon Moore,General,NaN,No
145,1047,John Campbell,67,F,2026-02-10,2024-06-21,Tanya Baxter,Orthopedics,NaN,N
159,1038,Lindsay Rodriguez,39,M,2025-10-23,2025-07-18,Troy Lynch,Orthopedics,NaN,0
176,1091,David Martinez,80,M,2025-09-13,2025-07-07,Amber Braun,Cardiology,NaN,Y
195,1087,Kimberly Guzman,31,F,2025-11-18,2025-04-02,Kristin Reeves,General,NaN,Y
196,1056,Terry Miller,24,F,2025-04-22,2025-03-24,John Lyons,General,NaN,Yes
206,1085,Clinton Estrada,75,M,2025-11-06,2024-10-14,Jacob Bender,Orthopedics,NaN,Y
208,1048,Walter Webb,33,NaN,2025-09-26,2024-09-03,Dale Herrera,Neurology,NaN,Y
233,1031,Kayla Berger,29,F,2025-08-05,2024-09-27,Todd Oconnor,Orthopedics,NaN,Y
238,1034,Kimberly Watson,60,F,2026-01-11,2025-07-25,Joseph Meyers,Neurology,NaN,0
261,1049,Robert Montoya,79,M,2025-12-06,2024-09-09,Gregg Bennett,Neurology,NaN,No
274,1054,Jason Harrington,62,M,2026-01-16,2025-07-14,Stacey Miller,Orthopedics,NaN,No
277,1017,Amber Trevino,86,F,2025-05-28,2024-07-10,Sarah Holder,Cardiology,NaN,1
297,1076,John Nguyen,23,M,2025-10-05,2025-03-20,David Robertson,General,NaN,No
342,1095,Nicholas Kelly,53,F,2026-03-23,2025-04-02,Paula Freeman,Cardiology,NaN,Y
349,1095,Summer Bishop,37,M,2025-10-21,2025-08-07,Cynthia Green,Cardiology,NaN,Yes
366,1082,Nichole Phillips,56,M,2025-09-17,2025-08-19,Michael Jackson,Cardiology,NaN,Y
370,1004,Sheryl Lopez,27,M,2025-08-26,2024-09-10,Barbara Alvarado,Neurology,NaN,Yes
371,1006,Shannon Ramos,42,M,2025-11-04,2024-11-05,James Huber,Orthopedics,NaN,Yes
425,1019,Eric Kim,33,F,2025-06-13,2024-06-09,Arthur Harris,General,NaN,No
430,1068,Yolanda Thomas,61,F,2025-12-15,2024-07-10,Keith Lee,Neurology,NaN,1
443,1016,Tyler Smith,42,M,2025-11-05,2024-08-03,Melinda Smith,General,NaN,Y
458,1037,David Reeves,52,M,2025-12-06,2025-01-19,Marc Copeland,General,NaN,N
529,1059,Valerie Vaughn,35,M,2025-11-11,2024-07-18,Felicia Warner,Orthopedics,NaN,0
537,1040,Tammy Nelson,20,M,2025-08-21,2024-04-15,Angel Aguilar,Cardiology,NaN,0
542,1024,Alejandra Perkins,72,NaN,2025-08-03,2025-04-11,Daniel Dickerson,Orthopedics,NaN,Y
547,1040,Kimberly Adkins,77,M,2025-12-15,2024-08-19,Tamara Rivera,Cardiology,NaN,0
558,1085,Linda Miller,28,F,2026-03-08,2024-12-08,Patricia White,Orthopedics,NaN,0
565,1084,Morgan Torres,83,M,2026-02-02,2025-07-29,April Lyons,General,NaN,0
598,1048,Elizabeth Russo,67,M,2025-07-03,2024-07-30,Connie Martinez,Neurology,NaN,Yes
664,1013,Zachary Allen,21,F,2026-02-24,2025-06-04,Justin Smith,Neurology,NaN,Yes
709,1058,Cassandra Peterson,34,M,2025-04-23,2024-12-08,Mary Sanchez,Orthopedics,NaN,1
745,1051,Kyle Jones,52,M,2025-10-31,2024-09-01,Sara Morse,Neurology,NaN,0
754,1044,Henry Henderson,58,M,2025-06-10,2024-08-02,James Love,Orthopedics,NaN,No
763,1081,Kimberly Fitzpatrick,65,F,2025-10-07,2024-12-09,Mark Moore,Orthopedics,NaN,No
791,1075,John Rich,48,F,2025-06-20,2024-09-05,Jennifer Johnston,General,NaN,1
796,1050,Amanda Johnston,46,F,2025-04-16,2024-10-24,Angela Burton,Cardiology,NaN,0
807,1041,Frank Castaneda,70,M,2025-07-26,2024-09-02,Christopher Chen,Neurology,NaN,0
817,1044,Sandra Rojas,83,M,2025-06-16,2025-03-07,Stephanie Bryant,Cardiology,NaN,No
819,1001,Erik Davis,30,M,2025-05-30,2024-12-05,Amanda White,Neurology,NaN,Yes
905,1016,Keith Douglas,49,M,2025-09-16,2025-05-02,Dawn Browning,Orthopedics,NaN,0
930,1041,Amy Wilson,81,M,2025-09-26,2025-02-01,Nathan Mathews,Orthopedics,NaN,0
933,1034,Amanda Douglas,90,M,2026-03-07,2024-06-25,Gregory Gonzalez,General,NaN,0
937,1048,Ashley Black,84,F,2025-05-29,2025-01-29,Dennis Murphy,Neurology,NaN,N
938,1068,Wendy Parks,40,M,2026-02-14,2025-09-09,Melissa Williams,Neurology,NaN,1
956,1016,Jocelyn Strickland,22,M,2025-04-30,2024-07-10,Vincent Kemp,Cardiology,NaN,N

In [18]:
currencies_symbols =['£', '€', 'Rs', '$']

for symbol in currencies_symbols:
    length = len(symbol)
    df ['billing_amount_'+symbol] = np.where(df['billing_amount'].str[0:length]==symbol ,
                                  (df['billing_amount'].str[length:]) ,
                                   0)

In [19]:
df[['billing_amount','billing_amount_£','billing_amount_$','billing_amount_Rs','billing_amount_€']]

,billing_amount,billing_amount_£,billing_amount_$,billing_amount_Rs,billing_amount_€
0,£425.8,425.8,0,0,0
1,€344.26,0,0,0,344.26
2,€203.34,0,0,0,203.34
3,Rs85.76,0,0,85.76,0
4,$84.44,0,84.44,0,0
...,...,...,...,...,...
995,Rs200.43,0,0,200.43,0
996,Rs244.49,0,0,244.49,0
997,£154.48,154.48,0,0,0
998,$434.95,0,434.95,0,0
999,€102.23,0,0,0,102.23

In [20]:
df['billing_amount'].unique()

array(['£425.8', '€344.26', '€203.34', 'Rs85.76', '$84.44', nan, '€99.0',
       'Rs374.63', '$452.37', '€494.97', '£91.91', '$82.88', 'Rs277.14',
       '€411.01', '£67.51', '€163.99', '£252.38', '$153.07', 'Rs329.3',
       '€135.45', 'Rs72.73', 'Rs258.64', '$203.61', 'Rs236.22',
       'Rs292.23', '$51.72', '£218.84', 'Rs160.38', 'Rs342.38',
       'Rs208.91', 'Rs426.86', '£215.31', '£413.53', '£396.22', '$340.25',
       '$481.44', '$442.77', 'Rs175.63', '€320.66', '$268.14', '€499.75',
       'Rs452.11', 'Rs479.77', '£213.35', 'Rs120.34', 'Rs135.43',
       '€214.44', 'Rs376.08', '€343.51', 'Rs185.66', '€200.01', '$367.06',
       'Rs393.4', '£387.4', '$169.25', '$274.81', 'Rs68.81', 'Rs365.13',
       '$466.97', 'Rs484.52', '€114.45', '€195.21', '$149.8', 'Rs270.33',
       '$186.24', 'Rs425.63', '£91.77', '€91.27', '£453.06', '€61.37',
       '$185.52', '£112.48', '$382.34', 'Rs168.18', '$206.53', '$258.21',
       '€253.4', 'Rs83.09', '$80.38', 'Rs260.4', '$294.58', '$247.13',
       '£341.19', 'Rs383.69', '€243.78', 'Rs329.25', '€389.37', '£344.56',
       'Rs289.07', 'Rs193.6', 'Rs259.72', '€235.69', '€428.75', '$142.32',
       '£109.31', '$325.25', '£111.92', '$347.68', '£59.67', 'Rs123.03',
       'Rs420.58', '€351.17', '£125.31', '€253.42', '€359.78', '$277.21',
       '£84.69', '€96.94', 'Rs205.35', 'Rs155.42', '$493.0', '$243.15',
       '€122.6', '£100.34', 'Rs335.07', '£154.29', '$412.07', 'Rs401.33',
       '$486.57', '£482.25', '€255.82', '€258.12', '$162.94', '£153.05',
       '£114.64', '£381.62', '£215.46', '$455.75', '£325.97', '$468.06',
       '£377.14', '$87.2', '$226.97', 'Rs139.81', '$466.08', 'Rs352.03',
       '$461.19', '£252.22', '£206.74', '$130.7', '£106.33', '$122.56',
       '£238.81', 'Rs413.21', '€91.87', '€485.5', '£209.81', '$401.55',
       'Rs283.3', '£146.2', '€211.18', '£476.99', '$248.33', '£192.67',
       '$65.06', '£117.14', 'Rs433.77', '$82.84', 'Rs216.23', '€492.98',
       'Rs280.77', '$99.19', '$225.83', '$458.12', '€244.78', '€330.37',
       '£98.14', '£464.69', '£91.65', 'Rs425.67', '€140.86', '$446.06',
       '£138.59', '£448.6', '€150.94', '€339.19', '€187.28', '€157.66',
       'Rs69.97', '£490.55', '€315.64', '£231.08', '$429.14', 'Rs93.12',
       '£461.81', '€130.72', 'Rs85.63', '€394.9', '£499.67', '€66.64',
       'Rs361.31', '£205.31', 'Rs193.18', '£321.34', '$446.44', '$165.8',
       'Rs493.59', '€489.64', '$96.48', '€422.79', 'Rs330.43', '£440.72',
       '€287.03', '€489.0', '£201.19', '€155.45', '£236.44', '$96.21',
       '€270.47', 'Rs284.29', '€354.36', '£452.69', '£329.83', '€450.86',
       'Rs132.38', '€199.55', '€296.7', '$409.96', '£386.53', 'Rs243.94',
       '$364.83', '$335.95', '€387.58', 'Rs360.39', '£288.24', '€286.43',
       '€476.26', '£480.75', 'Rs277.6', 'Rs301.11', '£304.51', '£266.53',
       'Rs433.55', '£70.47', '$425.91', '€111.71', '£365.37', '€475.27',
       '$108.6', '£455.05', '£264.45', 'Rs132.57', 'Rs359.5', 'Rs464.57',
       '$186.61', '$116.69', '€218.44', '€255.67', '$129.48', 'Rs299.03',
       'Rs459.66', '£403.61', '£241.48', '$417.38', 'Rs390.97', 'Rs100.2',
       '£462.97', '$481.92', '£350.41', 'Rs392.87', '$202.41', '$225.1',
       '€400.01', '$400.52', '£152.7', '€154.68', '$300.71', '£166.59',
       '£357.83', 'Rs458.11', '€85.07', '£209.67', '£239.39', 'Rs398.73',
       '€325.86', '$451.11', '£416.39', '€303.42', '$124.85', '$370.37',
       'Rs416.85', '£231.18', 'Rs119.4', '$63.38', 'Rs341.27', '$483.19',
       '€371.49', '€406.43', '€334.38', 'Rs125.6', '£377.85', '£450.24',
       '€382.81', '$424.21', '€258.38', 'Rs366.15', 'Rs466.92', '£114.67',
       'Rs71.67', 'Rs264.27', 'Rs92.45', 'Rs441.33', 'Rs258.78',
       'Rs156.71', 'Rs110.47', '€361.32', '€405.85', 'Rs496.78',
       '$364.33', 'Rs119.63', '£399.55', 'Rs186.4', 'Rs234.99',
       'Rs316.26', 'Rs129.91', '€468.01', 'Rs459.41', '€370.25',
       'Rs145.83', '$184.28', '£109.61', '$135.41', '£109.02', '$205.16',
       '$296.43', '$233.98', '€474.34', '£317.84', 'Rs435.55', 'Rs88.58',
       '€252.38', '$366.49', 'Rs239.5', 'Rs55.55', '£112.28', 'Rs386.16',
       '€230.73', '€296.85', '£64.79', '€101.1', 'Rs204.86', '$369.12',
       'Rs474.33', '€285.97', '€209.27', 'Rs347.87', '€98.07', 'Rs154.03',
       '£126.87', '£194.82', '€145.75', '€58.55', '$481.22', '€56.37',
       '£456.26', '$157.36', '$69.13', '€56.63', '$432.84', '£208.8',
       '$413.25', '$73.59', 'Rs466.72', '€213.67', '$156.9', '£323.18',
       '$188.72', '£411.32', '€388.8', '$296.8', '€439.46', '$320.72',
       '$262.84', 'Rs274.94', '£182.77', '€312.88', '£163.58', 'Rs135.85',
       '£242.2', '$374.72', '€326.58', '$379.39', 'Rs442.41', '€358.98',
       '£235.74', '$400.6', '€305.19', '£357.15', '$245.21', 'Rs498.26',
       'Rs499.72', '€315.71', '$149.33', '$412.82', '£372.5', '£60.76',
       '€290.52', 'Rs451.66', '£260.91', '$117.12', 'Rs460.11', '€91.94',
       '£347.38', 'Rs288.43', '€222.2', 'Rs180.6', '€485.31', '£255.9',
       '€443.13', 'Rs318.88', '$108.91', '£167.18', '£444.67', '$396.57',
       'Rs185.29', '$215.89', '£438.81', '€231.7', '£173.85', '$285.44',
       'Rs202.92', '€383.47', '£302.66', '£472.57', '€417.21', '$244.68',
       '$70.7', '€386.37', '$387.75', 'Rs176.68', 'Rs491.64', '$325.91',
       '$280.21', 'Rs88.29', '$443.75', '$385.61', 'Rs350.5', '$255.56',
       '£458.83', '€138.29', 'Rs189.02', '€272.47', '€450.37', '$490.67',
       '£99.17', '$105.64', '€437.18', 'Rs77.2', '€118.72', '€155.69',
       '$487.57', 'Rs412.44', '£297.5', '€481.4', '$252.53', '€167.8',
       'Rs347.94', '£305.02', '€83.61', '£360.39', '€402.4', '£234.26',
       'Rs219.5', '€191.19', 'Rs318.15', '$350.0', 'Rs178.28', '$248.31',
       'Rs352.72', '€208.03', '£116.75', '€91.29', '€198.61', '€257.17',
       '$343.79', '$431.21', '£241.91', '€95.25', '£167.07', '€426.64',
       '€106.8', '$478.18', 'Rs435.1', '€403.22', '€390.81', '£310.42',
       '$469.3', '€495.94', '€403.87', 'Rs466.56', '$163.52', 'Rs356.13',
       '$400.62', '$177.93', '£313.04', '£424.5', 'Rs222.37', '€349.49',
       '$482.2', 'Rs92.08', '€439.56', 'Rs473.48', '€151.02', 'Rs79.59',
       '£167.31', 'Rs194.81', '$97.67', '£254.91', '$169.09', 'Rs94.19',
       '£84.87', '$338.43', '$453.66', '£328.88', '£51.93', 'Rs201.8',
       '$129.1', '$153.53', 'Rs222.33', 'Rs403.78', '$343.21', '£67.97',
       'Rs365.21', '£269.53', '$163.58', 'Rs499.36', 'Rs101.37',
       '£442.72', '£224.89', 'Rs163.4', '€202.98', 'Rs257.1', '€466.87',
       '€490.78', 'Rs217.86', '$174.04', '€196.21', 'Rs490.08', '$91.94',
       '€484.82', '$175.26', 'Rs484.93', '$381.93', 'Rs402.6', 'Rs241.81',
       'Rs467.2', '£148.74', '£109.72', '£477.53', '€286.71', '£316.89',
       '€266.74', '£175.09', 'Rs96.2', 'Rs443.12', '$351.94', '$59.55',
       '£339.57', 'Rs344.57', '$197.72', '£202.68', '$95.4', '€245.84',
       '€284.66', 'Rs389.49', '$161.5', '£68.36', '£332.15', '£294.14',
       '€202.54', 'Rs455.57', '£378.58', '£110.44', '£274.12', 'Rs224.83',
       '$194.55', '€207.23', '€464.96', '£316.64', 'Rs139.49', '€447.23',
       '€320.38', '$212.66', 'Rs390.86', '$136.23', 'Rs68.8', '€79.41',
       'Rs224.61', '$190.44', '$316.64', 'Rs308.59', '$414.58', '€338.24',
       '€53.35', '$186.43', 'Rs268.93', '€322.0', '$498.84', 'Rs415.78',
       'Rs274.5', '£368.24', 'Rs353.07', '£358.68', '$427.54', 'Rs433.05',
       '€436.91', '€252.53', '$421.74', '£175.6', 'Rs203.05', '£123.13',
       '$337.15', '€180.76', '$445.97', '£236.58', '$125.33', '€394.58',
       '€96.12', 'Rs305.01', '$169.01', '€304.86', 'Rs426.51', '$215.76',
       '$184.11', 'Rs226.12', 'Rs277.5', 'Rs63.99', 'Rs85.56', '€237.1',
       '€250.69', '$421.57', '€77.79', '€156.32', '$249.74', '$126.56',
       '$143.32', '£353.8', '£174.54', '£217.77', 'Rs277.51', '£259.19',
       'Rs492.92', '€51.38', 'Rs374.03', '£175.33', '£129.25', 'Rs257.41',
       '€337.48', '€310.15', '€63.14', '$265.67', '$382.64', 'Rs125.35',
       '£206.69', '£358.45', '€496.62', 'Rs290.47', '€346.4', '$123.28',
       '$353.09', 'Rs299.12', '€286.79', '€330.76', '€69.76', '$341.11',
       '$147.08', '$462.6', '€357.53', 'Rs353.35', '£174.42', 'Rs449.41',
       '$179.07', 'Rs344.67', '$84.72', '£479.79', '€77.99', 'Rs113.2',
       '£363.04', '$477.72', 'Rs289.74', '$270.15', '£155.98', 'Rs335.27',
       'Rs285.22', 'Rs91.36', 'Rs498.58', '€453.73', '£218.54',
       'Rs312.26', '€159.21', '€484.79', 'Rs475.35', '$156.1', '$246.13',
       'Rs340.54', '$235.81', '£166.21', '€418.29', '£415.35', '$307.29',
       'Rs268.75', '€248.97', '$270.71', '$253.36', '$192.87', 'Rs362.08',
       '£306.62', '$348.18', '£298.42', '$473.2', '$124.09', '€52.32',
       '$151.03', 'Rs417.42', '$112.9', 'Rs126.44', '€185.15', '€258.9',
       '€477.08', '€306.8', 'Rs190.01', 'Rs281.44', 'Rs252.73', '£397.0',
       'Rs392.0', '€156.61', 'Rs81.87', '£438.16', '£447.77', '$139.99',
       '£393.1', '£248.78', '£453.09', '€57.05', '£386.04', '£204.82',
       '€239.93', 'Rs486.07', '€73.35', '£144.78', '€92.16', 'Rs164.9',
       '$74.84', 'Rs230.11', '€304.67', '£275.12', '€177.85', 'Rs410.8',
       '$97.46', 'Rs116.32', '$203.3', '$139.43', '$74.36', '€303.91',
       '$77.48', '€282.36', '£243.46', '€444.38', 'Rs319.04', '£330.71',
       'Rs160.18', '$290.14', '€244.09', '£150.5', '$398.47', '£262.16',
       '$142.33', 'Rs476.81', '€351.04', '£73.97', '$295.71', 'Rs167.5',
       '£321.5', '$168.33', '€411.75', '£462.15', '€124.69', '€129.38',
       '$488.54', '£93.45', '€73.45', '$340.47', '£414.94', '€238.05',
       'Rs63.62', '$101.59', '$498.48', '$305.84', 'Rs160.05', '$406.61',
       '£359.32', '$315.17', '£319.92', '£352.01', '£88.56', '$461.18',
       'Rs206.57', '£107.34', '$385.01', '£490.93', '$168.86', '$463.06',
       '$261.87', 'Rs170.53', '$197.66', '£454.23', '€104.3', '$263.1',
       '£229.44', '£424.53', '$248.84', '$89.38', '€110.8', '$217.51',
       '€427.98', '$298.89', '£182.71', '€350.12', '€158.91', '£457.94',
       '€130.9', '$318.44', 'Rs291.99', '$161.56', '€79.8', 'Rs151.58',
       'Rs338.13', '€441.92', 'Rs114.73', '£405.59', '$368.56',
       'Rs496.31', '€213.17', '€150.15', '€371.69', '$431.45', '£189.17',
       '$281.71', '€309.31', 'Rs57.03', 'Rs219.97', '£186.51', '€77.05',
       '£208.72', '£390.16', '£74.78', '$199.03', '£245.09', '£282.03',
       'Rs411.85', '£144.89', 'Rs198.95', 'Rs246.05', '€164.43',
       'Rs381.59', '€341.42', 'Rs456.12', 'Rs371.84', '€263.23',
       '$427.62', '£100.78', '£308.28', '€471.3', 'Rs437.95', 'Rs461.32',
       '€424.17', '€428.7', '€159.11', '$159.06', 'Rs317.16', '€470.63',
       '$153.44', '€416.08', '€458.79', '$125.8', 'Rs352.94', '€111.4',
       '€161.54', 'Rs479.37', '$306.94', '€194.95', '€91.05', '€290.36',
       '$85.53', '€419.74', '$83.67', 'Rs255.43', '$433.63', 'Rs461.04',
       '£261.01', 'Rs96.19', '£248.76', 'Rs246.63', 'Rs256.59', '$326.84',
       '£476.97', '$136.77', '€466.59', '€342.3', '€444.2', 'Rs421.18',
       '€386.3', 'Rs107.04', '£381.15', '€477.98', '€418.27', '€300.52',
       '£485.93', '£164.2', '$390.1', '£407.7', 'Rs467.55', '€119.41',
       '£441.89', 'Rs184.38', '$269.35', 'Rs363.94', '£323.0', '$163.0',
       'Rs254.14', '$112.79', 'Rs164.15', '€94.37', '$368.53', 'Rs240.37',
       '£238.59', 'Rs279.32', 'Rs114.8', '€96.78', '£384.42', 'Rs187.7',
       '£382.67', '€236.27', '$359.17', 'Rs362.65', '£401.58', '$120.7',
       '£405.15', '$263.3', '£470.08', '€79.73', '£376.76', 'Rs378.92',
       '$370.13', 'Rs377.38', 'Rs200.43', 'Rs244.49', '£154.48',
       '$434.95', '€102.23'], dtype=object)

In [21]:
df.drop(columns=['billing_amount'], inplace=True)

In [22]:
df

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,follow_up_required,billing_amount_£,billing_amount_€,billing_amount_Rs,billing_amount_$
0,1080,Tammy Williams,76,F,2026-02-26,2024-12-03,Christopher Graham,Cardiology,1,425.8,0,0,0
1,1074,Megan Strickland,69,F,2025-05-23,2024-06-12,Brandon Lewis,Orthopedics,Y,0,344.26,0,0
2,1067,Amanda Schroeder,79,M,2025-11-30,2024-08-05,Deanna Edwards,Neurology,Y,0,203.34,0,0
3,1072,Anthony Mcpherson,47,F,2025-05-18,2024-09-09,Karen Parsons,General,No,0,0,85.76,0
4,1092,Benjamin Brown,45,NaN,2026-03-07,2024-08-17,Andrea Hernandez,General,1,0,0,0,84.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1082,Thomas Roman,64,F,2025-09-14,2024-07-15,Robert Bass,General,Yes,0,0,200.43,0
996,1008,Jack Cooper,67,F,2025-04-09,2024-06-20,Christopher Smith,General,No,0,0,244.49,0
997,1022,Christopher Brown,28,M,2026-02-13,2024-06-13,Kimberly Johnson,Neurology,N,154.48,0,0,0
998,1088,Michael Sullivan,65,F,2025-07-04,2024-04-15,Anthony Mccoy,Neurology,0,0,0,0,434.95
999,1003,Perry Crawford,79,M,2025-11-05,2024-07-22,Marvin Hicks,Cardiology,Y,0,102.23,0,0

# Cleaning follow_up_required Column

In [23]:
df['follow_up_required'].unique()

array(['1', 'Y', 'No', 'Yes', 'N', '0'], dtype=object)

In [24]:
df['follow_up_required']= np.where (
    ( (df['follow_up_required']=='1') | (df['follow_up_required']=='Y') | (df['follow_up_required']=='Yes')),
1,
0)

In [25]:
df['follow_up_required'].unique()

array([1, 0])

In [26]:
df

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,follow_up_required,billing_amount_£,billing_amount_€,billing_amount_Rs,billing_amount_$
0,1080,Tammy Williams,76,F,2026-02-26,2024-12-03,Christopher Graham,Cardiology,1,425.8,0,0,0
1,1074,Megan Strickland,69,F,2025-05-23,2024-06-12,Brandon Lewis,Orthopedics,1,0,344.26,0,0
2,1067,Amanda Schroeder,79,M,2025-11-30,2024-08-05,Deanna Edwards,Neurology,1,0,203.34,0,0
3,1072,Anthony Mcpherson,47,F,2025-05-18,2024-09-09,Karen Parsons,General,0,0,0,85.76,0
4,1092,Benjamin Brown,45,NaN,2026-03-07,2024-08-17,Andrea Hernandez,General,1,0,0,0,84.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1082,Thomas Roman,64,F,2025-09-14,2024-07-15,Robert Bass,General,1,0,0,200.43,0
996,1008,Jack Cooper,67,F,2025-04-09,2024-06-20,Christopher Smith,General,0,0,0,244.49,0
997,1022,Christopher Brown,28,M,2026-02-13,2024-06-13,Kimberly Johnson,Neurology,0,154.48,0,0,0
998,1088,Michael Sullivan,65,F,2025-07-04,2024-04-15,Anthony Mccoy,Neurology,0,0,0,0,434.95
999,1003,Perry Crawford,79,M,2025-11-05,2024-07-22,Marvin Hicks,Cardiology,1,0,102.23,0,0

# Splitting appointment_date and booking_date Columns

In [27]:
dates= ['booking_date', 'appointment_date']

for d in dates:
    df[d+'_year'] = df[d].dt.year
    df[d+'_month'] = df[d].dt.month
    df[d+'_day'] =df[d].dt.day

In [28]:
df

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,follow_up_required,billing_amount_£,billing_amount_€,billing_amount_Rs,billing_amount_$,booking_date_year,booking_date_month,booking_date_day,appointment_date_year,appointment_date_month,appointment_date_day
0,1080,Tammy Williams,76,F,2026-02-26,2024-12-03,Christopher Graham,Cardiology,1,425.8,0,0,0,2024,12,3,2026,2,26
1,1074,Megan Strickland,69,F,2025-05-23,2024-06-12,Brandon Lewis,Orthopedics,1,0,344.26,0,0,2024,6,12,2025,5,23
2,1067,Amanda Schroeder,79,M,2025-11-30,2024-08-05,Deanna Edwards,Neurology,1,0,203.34,0,0,2024,8,5,2025,11,30
3,1072,Anthony Mcpherson,47,F,2025-05-18,2024-09-09,Karen Parsons,General,0,0,0,85.76,0,2024,9,9,2025,5,18
4,1092,Benjamin Brown,45,NaN,2026-03-07,2024-08-17,Andrea Hernandez,General,1,0,0,0,84.44,2024,8,17,2026,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1082,Thomas Roman,64,F,2025-09-14,2024-07-15,Robert Bass,General,1,0,0,200.43,0,2024,7,15,2025,9,14
996,1008,Jack Cooper,67,F,2025-04-09,2024-06-20,Christopher Smith,General,0,0,0,244.49,0,2024,6,20,2025,4,9
997,1022,Christopher Brown,28,M,2026-02-13,2024-06-13,Kimberly Johnson,Neurology,0,154.48,0,0,0,2024,6,13,2026,2,13
998,1088,Michael Sullivan,65,F,2025-07-04,2024-04-15,Anthony Mccoy,Neurology,0,0,0,0,434.95,2024,4,15,2025,7,4
999,1003,Perry Crawford,79,M,2025-11-05,2024-07-22,Marvin Hicks,Cardiology,1,0,102.23,0,0,2024,7,22,2025,11,5

In [29]:
df[['appointment_date','appointment_date_year','appointment_date_month','appointment_date_day']]
df.drop(columns=['appointment_date','booking_date' ], inplace=True)

In [30]:
df

,patient_id,patient_name,age,gender,doctor,department,follow_up_required,billing_amount_£,billing_amount_€,billing_amount_Rs,billing_amount_$,booking_date_year,booking_date_month,booking_date_day,appointment_date_year,appointment_date_month,appointment_date_day
0,1080,Tammy Williams,76,F,Christopher Graham,Cardiology,1,425.8,0,0,0,2024,12,3,2026,2,26
1,1074,Megan Strickland,69,F,Brandon Lewis,Orthopedics,1,0,344.26,0,0,2024,6,12,2025,5,23
2,1067,Amanda Schroeder,79,M,Deanna Edwards,Neurology,1,0,203.34,0,0,2024,8,5,2025,11,30
3,1072,Anthony Mcpherson,47,F,Karen Parsons,General,0,0,0,85.76,0,2024,9,9,2025,5,18
4,1092,Benjamin Brown,45,NaN,Andrea Hernandez,General,1,0,0,0,84.44,2024,8,17,2026,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1082,Thomas Roman,64,F,Robert Bass,General,1,0,0,200.43,0,2024,7,15,2025,9,14
996,1008,Jack Cooper,67,F,Christopher Smith,General,0,0,0,244.49,0,2024,6,20,2025,4,9
997,1022,Christopher Brown,28,M,Kimberly Johnson,Neurology,0,154.48,0,0,0,2024,6,13,2026,2,13
998,1088,Michael Sullivan,65,F,Anthony Mccoy,Neurology,0,0,0,0,434.95,2024,4,15,2025,7,4
999,1003,Perry Crawford,79,M,Marvin Hicks,Cardiology,1,0,102.23,0,0,2024,7,22,2025,11,5

# Preprocessing Other Columns

In [31]:
df['patient_id'].value_counts()

patient_id
1074    17
1047    17
1058    17
1015    17
1089    16
        ..
1096     4
1079     4
1023     4
1000     3
1007     3
Name: count, Length: 101, dtype: int64

In [32]:
df['doctor'].value_counts()

doctor
Nancy Hernandez       2
Nancy Wilson          2
Wesley Johnson        2
Kristen Lopez         2
James Aguilar         2
                     ..
Nathaniel Thompson    1
Natalie Turner        1
Kurt Cain             1
Laura Edwards         1
Alex Richards         1
Name: count, Length: 990, dtype: int64

In [33]:
df['department'].value_counts()

department
Neurology      273
Orthopedics    262
Cardiology     234
General        231
Name: count, dtype: int64

In [34]:
df.drop(columns=['patient_id','patient_name','doctor'], inplace=True)

In [35]:
df

,age,gender,department,follow_up_required,billing_amount_£,billing_amount_€,billing_amount_Rs,billing_amount_$,booking_date_year,booking_date_month,booking_date_day,appointment_date_year,appointment_date_month,appointment_date_day
0,76,F,Cardiology,1,425.8,0,0,0,2024,12,3,2026,2,26
1,69,F,Orthopedics,1,0,344.26,0,0,2024,6,12,2025,5,23
2,79,M,Neurology,1,0,203.34,0,0,2024,8,5,2025,11,30
3,47,F,General,0,0,0,85.76,0,2024,9,9,2025,5,18
4,45,NaN,General,1,0,0,0,84.44,2024,8,17,2026,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,64,F,General,1,0,0,200.43,0,2024,7,15,2025,9,14
996,67,F,General,0,0,0,244.49,0,2024,6,20,2025,4,9
997,28,M,Neurology,0,154.48,0,0,0,2024,6,13,2026,2,13
998,65,F,Neurology,0,0,0,0,434.95,2024,4,15,2025,7,4
999,79,M,Cardiology,1,0,102.23,0,0,2024,7,22,2025,11,5

In [36]:
df.describe()

,age,follow_up_required,booking_date_year,booking_date_month,booking_date_day,appointment_date_year,appointment_date_month,appointment_date_day
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,53.750000,0.514000,2024.496000,6.565000,15.536000,2025.240000,6.645000,15.994000
std,21.137604,0.500054,0.525605,3.230203,8.724151,0.427297,3.530643,8.830059
min,18.000000,0.000000,2024.000000,1.000000,1.000000,2025.000000,1.000000,1.000000
25%,34.000000,0.000000,2024.000000,4.000000,8.000000,2025.000000,3.000000,8.000000
50%,55.000000,1.000000,2024.000000,6.000000,15.000000,2025.000000,7.000000,16.000000
75%,71.000000,1.000000,2025.000000,9.000000,23.000000,2025.000000,10.000000,24.000000
max,90.000000,1.000000,2026.000000,12.000000,31.000000,2026.000000,12.000000,31.000000

# Converting Numeric String into Numbers

In [37]:
# ['billing_amount_£','billing_amount_€', 'billing_amount_Rs', 'billing_amount_$']

In [38]:
cols= np.array(['billing_amount_£','billing_amount_€', 'billing_amount_Rs', 'billing_amount_$'])

for col in cols:
    df[col] = pd.to_numeric( df[col] )

In [39]:
df[['billing_amount_£','billing_amount_€', 'billing_amount_Rs', 'billing_amount_$']].describe()

       billing_amount_£  billing_amount_€  billing_amount_Rs  billing_amount_$
count       1000.000000        1000.00000        1000.000000       1000.000000
mean          60.480940          64.76146          71.895490         65.173140
std          128.370313         133.17135         139.889644        132.353334
min            0.000000           0.00000           0.000000          0.000000
25%            0.000000           0.00000           0.000000          0.000000
50%            0.000000           0.00000           0.000000          0.000000
75%            0.000000           0.00000          58.677500          0.000000
max          499.670000         499.75000         499.720000        498.840000

In [40]:
df

,age,gender,department,follow_up_required,billing_amount_£,billing_amount_€,billing_amount_Rs,billing_amount_$,booking_date_year,booking_date_month,booking_date_day,appointment_date_year,appointment_date_month,appointment_date_day
0,76,F,Cardiology,1,425.80,0.00,0.00,0.00,2024,12,3,2026,2,26
1,69,F,Orthopedics,1,0.00,344.26,0.00,0.00,2024,6,12,2025,5,23
2,79,M,Neurology,1,0.00,203.34,0.00,0.00,2024,8,5,2025,11,30
3,47,F,General,0,0.00,0.00,85.76,0.00,2024,9,9,2025,5,18
4,45,NaN,General,1,0.00,0.00,0.00,84.44,2024,8,17,2026,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,64,F,General,1,0.00,0.00,200.43,0.00,2024,7,15,2025,9,14
996,67,F,General,0,0.00,0.00,244.49,0.00,2024,6,20,2025,4,9
997,28,M,Neurology,0,154.48,0.00,0.00,0.00,2024,6,13,2026,2,13
998,65,F,Neurology,0,0.00,0.00,0.00,434.95,2024,4,15,2025,7,4
999,79,M,Cardiology,1,0.00,102.23,0.00,0.00,2024,7,22,2025,11,5

# Imputing Missing Data in Gender

In [41]:
# imputing so that after encoding with one hot encoder can not produce gender_nan column.

In [42]:
non_nan_gender= df[df['gender'].isnull() == False]

In [43]:
 df['gender'].sample(n=2)

241    F
60     F
Name: gender, dtype: object

In [44]:
count = df['gender'].isnull().sum()

random_vals= df[ df['gender'].isnull() == False]['gender'].sample(n=count)#, replace=True)

df.loc[df['gender'].isnull() , 'gender'] =  random_vals.values
df['gender'].unique()

array(['F', 'M'], dtype=object)

# Encoding Categorical data to Numeric

In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 

ohe=  OneHotEncoder(drop='first')

ohe.set_output(transform="default")

trf= ColumnTransformer ([
    ('encoder',ohe, ['gender', 'department'])
],
    remainder = 'passthrough',
    verbose_feature_names_out=False
)

In [46]:
df=trf.fit_transform(df)

In [47]:
df

,gender_M,department_General,department_Neurology,department_Orthopedics,age,follow_up_required,billing_amount_£,billing_amount_€,billing_amount_Rs,billing_amount_$,booking_date_year,booking_date_month,booking_date_day,appointment_date_year,appointment_date_month,appointment_date_day
0,0.0,0.0,0.0,0.0,76.0,1.0,425.80,0.00,0.00,0.00,2024.0,12.0,3.0,2026.0,2.0,26.0
1,0.0,0.0,0.0,1.0,69.0,1.0,0.00,344.26,0.00,0.00,2024.0,6.0,12.0,2025.0,5.0,23.0
2,1.0,0.0,1.0,0.0,79.0,1.0,0.00,203.34,0.00,0.00,2024.0,8.0,5.0,2025.0,11.0,30.0
3,0.0,1.0,0.0,0.0,47.0,0.0,0.00,0.00,85.76,0.00,2024.0,9.0,9.0,2025.0,5.0,18.0
4,1.0,1.0,0.0,0.0,45.0,1.0,0.00,0.00,0.00,84.44,2024.0,8.0,17.0,2026.0,3.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,1.0,0.0,0.0,64.0,1.0,0.00,0.00,200.43,0.00,2024.0,7.0,15.0,2025.0,9.0,14.0
996,0.0,1.0,0.0,0.0,67.0,0.0,0.00,0.00,244.49,0.00,2024.0,6.0,20.0,2025.0,4.0,9.0
997,1.0,0.0,1.0,0.0,28.0,0.0,154.48,0.00,0.00,0.00,2024.0,6.0,13.0,2026.0,2.0,13.0
998,0.0,0.0,1.0,0.0,65.0,0.0,0.00,0.00,0.00,434.95,2024.0,4.0,15.0,2025.0,7.0,4.0
999,1.0,0.0,0.0,0.0,79.0,1.0,0.00,102.23,0.00,0.00,2024.0,7.0,22.0,2025.0,11.0,5.0

In [48]:
df.isnull().sum()

gender_M                  0
department_General        0
department_Neurology      0
department_Orthopedics    0
age                       0
follow_up_required        0
billing_amount_£          0
billing_amount_€          0
billing_amount_Rs         0
billing_amount_$          0
booking_date_year         0
booking_date_month        0
booking_date_day          0
appointment_date_year     0
appointment_date_month    0
appointment_date_day      0
dtype: int64

In [49]:
df

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (df.drop(columns=['follow_up_required'], inplace=False ), df['follow_up_required'], test_size=0.25, random_state=42)

# Train with Logistic Regression

In [50]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression (max_iter=3580)
reg.fit(X_train, y_train)

LogisticRegression(max_iter=3580)

In [51]:
predicted_y= reg.predict(X_test)

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(predicted_y , y_test)

0.464

# Train with Decision Tree

In [53]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

In [54]:
predicted_y= dtree.predict(X_test)
accuracy_score (predicted_y, y_test)

0.528

***This dataset is just synthethic one and can not be used for appointment prediction, (because there is not relationship btw input features and target feature). So this dataset is just for practice of cleaning data / data engineering.***